site_name: Rye
site_description: An Experimental Package Management Solution for Python
repo_name: mitsuhiko/rye
repo_url: https://github.com/mitsuhiko/rye
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 Armin Ronacher

nav:
  - Welcome: index.md
  - User Guide:
    - guide/index.md
    - Installation: guide/installation.md
    - Basics: guide/basics.md
    - Configuration: guide/config.md
    - Python Project: guide/pyproject.md
    - Syncing and Locking: guide/sync.md
    - Dependencies: guide/deps.md
    - Toolchains: guide/toolchains.md
    - Tools: guide/tools.md
  - Community: community.md
  - Changelog: changelog.md
  - Philosophy: philosophy.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
  font:
    text: Inter
    monospace: Fira Mono
  favicon: static/favicon.svg
  logo: static/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - markdown_include.include:
      base_path: docs
  - mdx_gh_links:
      user: mitsuhiko
      repo: rye

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_get"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mitsuhiko
      name: Follow @mitsuhiko on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@mitsuhiko
      name: Follow @mitsuhiko on Twitter
    - icon: material/alpha-b-box
      link: https://bsky.app/profile/mitsuhiko.at
      name: Follow @mitsuhiko.at on Bluesky
    - icon: fontawesome/brands/discord
      link: https://discord.gg/drbkcdtSbg
      name: Discuss Rye on Discord

extra_css:
  - static/extra.css
